# These are supported funding model platforms

github: Burnsedia
patreon: BaileyBurnsed
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Burnsedia
issuehunt: burnsedia
otechie: # Replace with a single Otechie username
custom: ['https://burnsedia.itch.io/the-hive','https://www.buymeacoffee.com/dashboard','https://www.bountysource.com/teams/the-hive']
